### ISSUE TITLE
Generate diagramms in a separate folder

### ISSUE THREAD

**Issue by tomasson82** [TimKolberger/docusaurus-plugin-structurizr#122]
### Description

The diagrams are generated and saved at the same path where the `structurizr.dsl` is saved. 
Moving the generated files to a separated folder will support clarity.

### Problem Statement/Justification

When you generate several diagrams you will loose clarity of your folder. 
Separating the generated files from the files to edit might be a good pattern.

### Proposed Solution or API

Using the the output option of [structurizr-cli](https://docs.structurizr.com/cli/export#options) in export function call would be great:
https://github.com/TimKolberger/docusaurus-plugin-structurizr/blob/9d5135b6090a361bdc17acbcd9fd996959a05eef/packages/docusaurus-plugin-structurizr/src/run-structurizr.ts#L22 

`docker run --rm -v "${docsPath}:/usr/local/structurizr" ${dockerImage} export -workspace "${fileName}" -output diagrams`

[Optional] the destination folder could become an option of the plugin.

**Comment by TimKolberger** [comment]
Released in [docusaurus-plugin-structurizr@0.5.0](https://github.com/TimKolberger/docusaurus-plugin-structurizr/releases/tag/docusaurus-plugin-structurizr%400.5.0)
